export const OPS_ROUTE_GROUPS = [
  { key: 'home', label: '概览', icon: 'space_dashboard' },
  { key: 'scan', label: '扫码执行', icon: 'qr_code_scanner' },
  { key: 'warehouse', label: '仓储作业', icon: 'warehouse' },
  { key: 'design', label: '部门协同', icon: 'design_services' },
]

export const OPS_ROUTE_REGISTRY = [
  {
    key: 'dashboard',
    groupKey: 'home',
    path: '',
    routePath: '',
    exact: true,
    moduleId: 'home',
    componentKey: 'home',
    navigation: true,
    icon: 'space_dashboard',
    shortLabel: 'HM',
    label: '执行工作台',
    description: '当前上下文、执行入口与待处理动作',
    cardDescription: '查看扫码、发放和仓储作业入口。',
    title: '执行工作台',
    summary: '',
    sectionLabel: '执行端',
    surfaceCode: 'OPS',
  },
  {
    key: 'scan',
    groupKey: 'scan',
    path: '/scan',
    routePath: 'scan',
    moduleId: 'scan',
    componentKey: 'scan',
    navigation: true,
    icon: 'qr_code_scanner',
    shortLabel: 'SC',
    label: '通用扫码',
    description: '号码布与证件扫码入口',
    cardDescription: '扫号码布或证件，核验后继续处理。',
    title: '执行端扫码',
    summary: '扫号码布或证件，核验后继续处理。',
    sectionLabel: '扫码执行',
    surfaceCode: 'OPS',
  },
  {
    key: 'scan-result',
    groupKey: 'scan',
    path: '/scan/result',
    routePath: 'scan/result',
    moduleId: 'scan',
    componentKey: 'scan-result',
    title: '扫码结果',
    summary: '展示扫码命中结果并执行后续动作。',
    sectionLabel: '扫码执行',
    surfaceCode: 'OPS',
  },
  {
    key: 'bibs',
    groupKey: 'scan',
    path: '/bibs/pickup',
    routePath: 'bibs/pickup',
    moduleId: 'bib-pickup',
    componentKey: 'bib-pickup',
    navigation: true,
    icon: 'confirmation_number',
    shortLabel: 'BB',
    label: '号码布领取',
    description: '号码布领取与核验',
    cardDescription: '选手现场领取号码布、扫码核验身份并确认发放。',
    title: '号码布领取',
    summary: '号码布现场扫码与领取确认。',
    sectionLabel: '扫码执行',
    surfaceCode: 'OPS',
  },
  {
    key: 'credentials',
    groupKey: 'scan',
    path: '/credentials/issue',
    routePath: 'credentials/issue',
    moduleId: 'credentials',
    componentKey: 'credential-issue',
    navigation: true,
    icon: 'badge',
    shortLabel: 'CR',
    label: '证件发放',
    description: '证件发放与状态更新',
    cardDescription: '发放工作人员、志愿者等证件，并更新状态。',
    title: '证件发放',
    summary: '证件发放、领取和状态更新。',
    sectionLabel: '扫码执行',
    surfaceCode: 'OPS',
  },
  {
    key: 'workbench',
    groupKey: 'warehouse',
    path: '/warehouse',
    routePath: 'warehouse/*',
    moduleId: 'warehouse',
    componentKey: 'warehouse',
    navigation: true,
    icon: 'inventory_2',
    shortLabel: 'WH',
    label: '仓储作业台',
    description: '入库、出库、库位绑定与盘点',
    cardDescription: '处理入库、出库、库位绑定、盘点和异常。',
    title: '仓储作业台',
    summary: '处理入库、出库、库位绑定、盘点和异常。',
    sectionLabel: '仓储作业',
    surfaceCode: 'OPS',
  },
  ...[
    ['warehouse-inbound', '/warehouse/inbound', '入库作业', '预入库、批量入库与标签处理。'],
    ['warehouse-outbound', '/warehouse/outbound', '出库作业', '出库、领取与扫码处理。'],
    ['warehouse-binding', '/warehouse/binding', '库位绑定', '数字孪生库位绑定、移位与解绑。'],
    ['warehouse-count', '/warehouse/count', '盘点作业', '盘点与异常处置。'],
  ].map(([key, path, title, summary]) => ({
    key,
    groupKey: 'warehouse',
    path,
    moduleId: 'warehouse',
    title,
    summary,
    sectionLabel: '仓储作业',
    surfaceCode: 'OPS',
  })),
  {
    key: 'design-requests',
    groupKey: 'design',
    path: '/design-requests',
    routePath: 'design-requests',
    moduleId: 'design-requests',
    componentKey: 'design-requests',
    navigation: true,
    icon: 'add_photo_alternate',
    shortLabel: 'DR',
    label: '设计需求',
    description: '提交组织级设计 brief 并查看处理进度',
    cardDescription: '提交设计需求，填写尺寸、材质、时间和关联赛事。',
    title: '设计需求',
    summary: '提交设计需求，关联赛事，并查看审批和设计进度。',
    sectionLabel: '部门协同',
    surfaceCode: 'OPS',
  },
]

export function listOpsNavigationRoutes() {
  return OPS_ROUTE_REGISTRY.filter((route) => route.navigation)
}

export function listOpsComponentRoutes() {
  return OPS_ROUTE_REGISTRY.filter((route) => route.componentKey)
}
