export const BUILTIN_STUDIO_ASSET_TEMPLATES = [
    {
        id: 'builtin-stage-platform',
        orgId: null,
        kind: 'parametric',
        category: 'stage',
        name: '组合舞台',
        thumbnailUrl: null,
        parametersSchema: {
            widthMm: { type: 'number', min: 1000, max: 24000 },
            depthMm: { type: 'number', min: 1000, max: 12000 },
            heightMm: { type: 'number', min: 200, max: 2000 },
            color: { type: 'string' },
        },
        defaultParameters: {
            widthMm: 4880,
            depthMm: 2440,
            heightMm: 600,
            color: '#2f3a4f',
        },
        modelUrl: null,
        source: 'builtin',
    },
    {
        id: 'builtin-truss-segment',
        orgId: null,
        kind: 'parametric',
        category: 'structure',
        name: '桁架段',
        thumbnailUrl: null,
        parametersSchema: {
            widthMm: { type: 'number', min: 200, max: 1000 },
            depthMm: { type: 'number', min: 200, max: 1000 },
            heightMm: { type: 'number', min: 500, max: 6000 },
        },
        defaultParameters: {
            widthMm: 300,
            depthMm: 300,
            heightMm: 2000,
        },
        modelUrl: null,
        source: 'builtin',
    },
    {
        id: 'builtin-event-tent',
        orgId: null,
        kind: 'parametric',
        category: 'structure',
        name: '赛事篷房',
        thumbnailUrl: null,
        parametersSchema: {
            widthMm: { type: 'number', min: 3000, max: 12000 },
            depthMm: { type: 'number', min: 3000, max: 24000 },
            heightMm: { type: 'number', min: 2500, max: 8000 },
        },
        defaultParameters: {
            widthMm: 6000,
            depthMm: 6000,
            heightMm: 3800,
        },
        modelUrl: null,
        source: 'builtin',
    },
    {
        id: 'builtin-crowd-barrier',
        orgId: null,
        kind: 'parametric',
        category: 'control',
        name: '铁马护栏',
        thumbnailUrl: null,
        parametersSchema: {
            widthMm: { type: 'number', min: 1000, max: 3000 },
            heightMm: { type: 'number', min: 800, max: 1600 },
        },
        defaultParameters: {
            widthMm: 2000,
            heightMm: 1100,
        },
        modelUrl: null,
        source: 'builtin',
    },
    {
        id: 'builtin-storage-rack',
        orgId: null,
        kind: 'parametric',
        category: 'storage',
        name: '标准托盘货架',
        thumbnailUrl: null,
        parametersSchema: {
            widthMm: { type: 'number', min: 1800, max: 4000 },
            depthMm: { type: 'number', min: 600, max: 1800 },
            heightMm: { type: 'number', min: 1800, max: 5000 },
            levels: { type: 'number', min: 1, max: 8 },
        },
        defaultParameters: {
            widthMm: 2400,
            depthMm: 1000,
            heightMm: 3200,
            levels: 4,
        },
        modelUrl: null,
        source: 'builtin',
    },
    {
        id: 'builtin-checkin-desk',
        orgId: null,
        kind: 'parametric',
        category: 'furniture',
        name: '签到台',
        thumbnailUrl: null,
        parametersSchema: {
            widthMm: { type: 'number', min: 1000, max: 4000 },
            depthMm: { type: 'number', min: 400, max: 1600 },
            heightMm: { type: 'number', min: 700, max: 1400 },
        },
        defaultParameters: {
            widthMm: 1800,
            depthMm: 700,
            heightMm: 1050,
        },
        modelUrl: null,
        source: 'builtin',
    },
];
